version: "3"

volumes:
  postgres_volume:

services:
  back-end:
    container_name: private_notes-container
    # image: todo-backend:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - private_notes-networks
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/private_notes
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:12-alpine'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_USER=compose-postgres

networks: 
  private_notes-networks:
    driver: bridge